name = "Cleanroom Modpack"
author = "samueltobiasmartinez09"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1de26994075981a3521e24a1398912cde61f4a3648d8ba7c7e79cc386d6a25a7"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
