name = "Cleanroom Modpack"
author = "samueltobiasmartinez09"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "45155c56b74070d398aee2c218e922a4ba01e295de54c7a44e441d819f6e8147"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
