name = "Cleanroom Modpack"
author = "samueltobiasmartinez09"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8c5e0c532c4d7366e4e5fb6fd0fa1af236d7f858dbd68a610b50adb3b4d75267"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
